### ISSUE TITLE
Server doesn't work [URGENT]

### ISSUE THREAD

**Issue by dresiarz222** [ModByDaylight/PrivateServer#17]
When i try to start it says - missing "The Onryo modules" and crashes the game.

**Comment by dresiarz222** [comment]
This is most likely caused by the new killer, Sadako

**Comment by jameszaza077** [comment]
Please wait for the new version of the private server.

**Comment by merakib** [comment]
> When i try to start it says - missing "The Onryo modules" and crashes the game.

Wait for new releases
New update has fixed <_<
