### ISSUE TITLE
No Network Connection

### ISSUE THREAD

**Issue by davidisatwat** [ModByDaylight/PrivateServer#23]
on the most recent update, cannot connect to servers. live game still works tho

**Comment by BrandonItaly** [comment]
This is a server sided issue and will be fixed when the Private Server API is moved to VPS.

**Comment by davidisatwat** [comment]
okay thank u :)))

is there a time frame for when this might be ?

**Comment by BrandonItaly** [comment]
Should be sometime tomorrow

**Comment by davidisatwat** [comment]
yay thank u :))
